language: haskell
cabal: "2.2"
ghc:
  - "8.0.2"
  - "8.2.2"
  - "8.4.4"
  - "8.6.5"
  - "8.8.3"
  - "8.10.1"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libx11-dev libxrandr-dev
