name: Update Nixpkgs

on:
  push:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  experimental-build:
    name: Experimental Build
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        nixpkgs: [ nixpkgs-unstable, nixos-unstable ]
        ghc: [ ghc948 ]
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2.3.4
    - name: Set up nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:${{ matrix.nixpkgs }}
    - name: Run nix-build
      run: nix-build --argstr ghcVersion ${{ matrix.ghc }} --arg nixpkgs "import <nixpkgs>"

  default-build:
    name: Default Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nixpkgs: [ nixpkgs-unstable, nixos-unstable ]
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2.3.4
    - name: Set up nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:${{ matrix.nixpkgs }}
    - name: Run nix-build
      run: nix-build --arg nixpkgs "import <nixpkgs>"
