name: "test"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: [ ghc884, ghc8104, ghc901 ]

    steps:
    - name: Setup GitHub Actions
      uses: actions/checkout@v2.3.4
    - name: Setup nix
      uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - run: nix-build --argstr ghcVersion ${{ matrix.ghc }}
