name: "test"

on:
  pull_request:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ghc: [ ghc884, ghc8104, ghc901 ]

    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v2.3.4

    - name: Set up nix
      uses: cachix/install-nix-action@v13

    - name: Run nix-build
      run: nix-build --argstr ghcVersion ${{ matrix.ghc }}
